### ISSUE TITLE
Missing "SpriteKit" headers

### ISSUE THREAD

**Issue by siuying** [kishikawakatsumi/JavaScriptBridge#20]
I just found SpriteKit for iOS is missing from the frameworks bundled. How the header files are created? Is it possible to create some kind of generator to do that?

**Comment by kishikawakatsumi** [comment]
The auto-generated headers for SpriteKit have some problems to JSExport compliant.
Also I think there are few people who use SpriteKit with JavaScript.
So I put it lower priorities.

If you want to use SpriteKit with JS, I will try to fix it.

**Comment by siuying** [comment]
Yes! Thanks! I was trying to make a interactive demo with it.

**Comment by kishikawakatsumi** [comment]
Done https://github.com/kishikawakatsumi/JavaScriptBridge/pull/22

I also added a simple example code.
https://github.com/kishikawakatsumi/JavaScriptBridge/blob/master/Examples/UICatalog/UICatalog/js/spritesViewController.js

But I am not good at SpriteKit.framework.
If you find any problem, please tell me that.

Thanks.

**Comment by siuying** [comment]
Awesome! I'll check it out, thanks.
