### ISSUE TITLE
`define` vs `createClass`

### ISSUE THREAD

**Issue by basecode** [kishikawakatsumi/JavaScriptBridge#3]
Hi! I propose changing the API `JSB.define` to `JSB.createClass`. Because…
- `define` conflicts with the naming convention of [AMD](http://requirejs.org/docs/whyamd.html#amd)
- Confusing since you're already using CommonJS naming convention (require/exports) 
- `createClass` is more explicit

PS: Looking forward using your Library!

**Comment by kishikawakatsumi** [comment]
Thank you for your advice.
I will consider to change method name.
Probably to be changed soon.

**Comment by kishikawakatsumi** [comment]
How about `defineClass` ?

**Comment by basecode** [comment]
Sure, I'm fine with that, too. I proposed `create` because it seems to be a naming convention within JS API. E.g. it's called `Object.create` and not `Object.define`. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create

**Comment by kishikawakatsumi** [comment]
Thank you for your proposal.
I choose `defineClass`.

`define` method is still remained for backward compatibility but deprecated.
It will be removed sometime soon.

**Comment by basecode** [comment]
Great!
