### ISSUE TITLE
Make UISwipeGestureRecognizer JavaScript Compliant

### ISSUE THREAD

**Issue by bsorrentino** [kishikawakatsumi/JavaScriptBridge#8]
Hi 

I'm trying to use  UISwipeGestureRecognizer but it isn't JavaScript compliant

Any chance to fix it ?

**Comment by kishikawakatsumi** [comment]
Thank you for report.

Because of some methods (as shown below) have `SEL` type argument. 
These methods could not be exported to JS.

```
- (id)initWithTarget:(id)target action:(SEL)action;
- (void)addTarget:(id)target action:(SEL)action;
- (void)removeTarget:(id)target action:(SEL)action;
```

I will fix it soon.

**Comment by kishikawakatsumi** [comment]
Done. https://github.com/kishikawakatsumi/JavaScriptBridge/pull/9

I had tested and confirmed to work with the code shown below.
(Swiping the red view, `swiped.` shown in console.)

If there is any problems, please ask me.
Thanks.

``` JavaScript
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    JSContext *context = [JSBScriptingSupport globalContext];

    [context evaluateScript:
     @"var window = UIWindow.new();"
     @"window.frame = UIScreen.mainScreen().bounds;"
     @"window.backgroundColor = UIColor.whiteColor();"
     @""
     @"var navigationController = UINavigationController.new();"
     @"var viewController = UIViewController.new();"
     @"viewController.navigationItem.title = 'Make UI with JavaScript';"
     @""
     @"var view = UIView.new();"
     @"view.backgroundColor = UIColor.redColor();"
     @"view.frame = {x: 20, y: 80, width: 280, height: 80};"
     @""
     @"var MyObject = JSB.defineClass('MyObject : NSObject', {"
     @"  onSwipe: function(sender) {"
     @"    JSB.dump('swiped.');"
     @"  }"
     @"});"
     @""
     @"var obj = MyObject.new();"
     @"var recognizer = UISwipeGestureRecognizer.alloc().initWithTargetAction(obj, 'onSwipe:');"
     @"view.addGestureRecognizer(recognizer);"
     @""
     @"viewController.view.addSubview(view);"
     @""
     @"navigationController.viewControllers = [viewController];"
     @""
     @"window.rootViewController = navigationController;"
     @"window.makeKeyAndVisible();"
     ];

    return YES;
}
```

**Comment by bsorrentino** [comment]
Looks great!

I'll test it soon

**Comment by bsorrentino** [comment]
Hi 

executing 

``` javascript
    var MyObject =
    JSB.defineClass('MyObject : NSObject', {

                    onSwipe: function(sender) {
                        JSB.dump('swiped.');
                    }
                });



    var obj = MyObject.new();
```

I got error:

<pre>
TypeError: 'undefined' is not an object (evaluating '__JSB_JSBScriptingSupport.defineClass(declaration, instanceMembers, staticMembers)')
</pre>

I don't understand why... any thought ?

Thanks in advance

**Comment by kishikawakatsumi** [comment]
I had found a mistake in auto-generated JSExport header for UIGestureRecognizer.
It is fixed at 39e60124f19ed0442eada37a979627a5746e43e1.

Also I created sample code for gesture recognizers.
It is in UICatalog project. 
https://github.com/kishikawakatsumi/JavaScriptBridge/blob/master/Examples/UICatalog/UICatalog/js/gestureViewController.js

Please try it.

**Comment by bsorrentino** [comment]
Hi

Your code works ... but there is a little problem in my case

I've defined a  custom **context.exceptionHandler**  because i need to understand if there are 
exceptions during script evaluation & execution.

But evaluating your script, also if it works, the exceptionHandler catch the following exception

<pre>
[TypeError: 'undefined' is not an object (evaluating '__JSB_JSBScriptingSupport.defineClass(declaration, instanceMembers, staticMembers)')]
</pre>

I've seen that you have disabled it 

``` java
globalContext.exceptionHandler = ^(JSContext *context, JSValue *value) {}; 
```

Is it normal? There is any way to avoid such exception

Thx in advance

**Comment by kishikawakatsumi** [comment]
OK, it make sence.

```
[TypeError: 'undefined' is not an object (evaluating '__JSB_JSBScriptingSupport.defineClass(declaration, instanceMembers, staticMembers)')]
```

This exception occurred due to pass undefined value to defineClass method.
(`staticMembers` is often not passed.)
It is fixed passing empty object as a default parameter.
https://github.com/kishikawakatsumi/JavaScriptBridge/pull/16

And also exception generated due to export same named methods/properties.
(For example, UITableView and UIScrollView has delegate property both.)

It is also fixed in https://github.com/kishikawakatsumi/JavaScriptBridge/pull/17.

**Comment by bsorrentino** [comment]
It works!

Now i'm able to catch real exceptions

thank you for support and for keep, this great project, on track
